mob/Stat()
	statpanel("Stats")
	stat("Level:","[src.lvl]")
	stat("EXP:","[src.exp]/[src.nxp]")
	stat("Health:","[src.HP]/[src.maxHP]")
	stat("Strength:","[src.str]")
	stat("Defense:","[src.def]")
	stat("Upgrade points:","[src.upgPnt]")
	stat("Total defense:","[src.def*src.dBoost]")
	stat("Total power:","[src.str*src.sBoost]")
	stat("S (Currency):","[src.money]")
	stat("Kills of all mobs:","[src.kills]")
	statpanel("Inventory", contents)